### ISSUE TITLE
Adding Products to a Shopping Bag

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#14]
As a **Shopper** I can **add products with different quantities** so that I can **purchase them all together when I am finished shopping**

**Acceptance Criteria**
- Within the product detail page the shopper will see an Add to Bag and quantity selector
- When the user clicks the add to bag, the product in the selected quantity is added to the shopping bag
- The user is prevented from adding quantities outside the minimum or maximum amounts
 
**Tasks**
- [ ]  Create add to bag form in the product detail html template
- [ ]  Create add to bag view and url
- [ ]  Add the bag content to the context processor
- [ ]  Add javascript to increase/decrease quantity in bag, ensuring quantity cannot go below 0, or above the maximum quantity
- [ ]  Style add to bag button and the quantity selector
