### ISSUE TITLE
Shopping Bag - See current spend so far

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#15]
As a **Shopper** I can **see how much I have spent so far** so that I can **see how much my bag costs currently**

**Acceptance Criteria**
- As the user adds products, the user can see a message showing the item has been added, and showing what's currently in their bag and the total cost so far
 
**Tasks**
- [x]  Create a toast HTML template for the success message
- [x]  Add the success message to add to bag view
- [x]  Include the Shopping bag current total in the success HTML template
