### ISSUE TITLE
Shopping bag - delete or update quantity of Products

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#17]
As a **Shopper** I can **delete or update quantities of products in my bag** so that I can **adjust my purchases before checking out**

**Acceptance Criteria**
- The user is able to adjust quantities of Product items 
- The user is able to delete an item from their bag
- The total of the bag cost is updated accordingly
-  
**Tasks**
- [x] Add quantity selector buttons and update/delete buttons to the shopping bag page
- [x] Add javascript to increase/decrease the quantity when the button is clicked
- [x] Add javascript to update the cart when the update button is clicked
- [x] Add javascript to delete the product line items when delete button is clicked
- [x] Create 'adjust bag' and 'delete item' views and urls
