### ISSUE TITLE
View Shopping Bag

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#19]
As a **Shopper** I can **view the contents of my shopping bag** so that I can **see what products I have selected, their cost and the delivery cost**

**Acceptance Criteria**
- On the navigation bar, there is a shopping bag icon that brings the user to the shopping bag page
- The shopping bag page shows the products which the user has added to their cart, unit price, quantity, subtotal
- The user should be able to increase/decrease the quantity of items in the bag
- The bag total, delivery costs and then the grand total are displayed at the bottom of the page
- The user has the option to checkout or to continue shopping

**Tasks**
- [ ] Create the bag app, HTML template and url
- [ ] Create the view_bag view
- [ ] Add a link to shopping bag in the navigation bar
- [ ] Create context.py in the bag app and add to settings.py.
- [ ] Style bag.html page
