### ISSUE TITLE
View a list of Products with pagination

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#2]
As a **Site User**, I can **view a paginated list of Products** so that I can **view and browse a list of Products**

**Acceptance Criteria**
- On the main articles page the user can see a list view of each Product with summary information 
- The user can clearly see what each Product is for
- When the user clicks on a Product, they get a details view of the Products full information

**Tasks**
- [ ]  Create a Product class in views.py to show a list view of the Products
 - [ ]  Create a browse HTML template
- [ ]   Create a layout that is both responsive and easy to view the basic information of each Product
- [ ]   Link the Summary Product view to the Full Product details
 - [ ]  Add pagination
