### ISSUE TITLE
Email confirmation of order

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#22]
As a **Shopper** I can **receive and email confirming my order** so that I can **know I have checked out successfully and see a summary of my purchases, that I can keep as a record**

**Acceptance Criteria**
- Upon successful submission of an order, a confirmation email is sent to the email address on the order, with details of the order

**Tasks**
- [x] Create an email template with order confirmation and summary of order
- [x] Update webhook to handle sending a confirmation email
- [x] Set up Gmail to send an email
