### ISSUE TITLE
Admin - Product Management

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#23]
As a **Admin** I can **easily Add, Edit and Delete Products** so that I can **manage the content of the store**

**Acceptance Criteria**
- When logged in as an Admin, a Product Management option is available in the navigation bar
- On the Product Management page, the Admin can fill in a user friendly form to add a new product
- Under product details, an Admin will find edit and delete product buttons
- The add/edit forms should contain fields for all required information and should include form validation with feedback if the form is not valid
- The Admin will be asked to confirm before deleting a product
- The Admin will receive a success message when a product is added, updated or deleted

**Tasks**
- [ ] Create product form.py
 - [ ] Create html pages for add product, edit product and confirm delete product
 - [ ] Write add/edit/delete product views and include form validation
- [ ]  Include error/success messages to give feedback to the Admin
 - [ ] Add edit and delete buttons to product summary and product detail page
 - [ ] Create an "Add Product" button on navigation
