### ISSUE TITLE
Newsletter sign up

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#26]
As a **site user** I can **sign up for the site's newsletter** so that I can **keep up to date with products and promotions**

**Acceptance Criteria**
- The footer will contain a newsletter sign up section, where the user can enter their email address to sign up
- The user's email will be added to a mailchimp mailing list

**Tasks**
- [x] set up Mailchimp account
- [x] Add mailchimp html and javascript to the footer
- [x] Add styling to footer section
