### ISSUE TITLE
View Product's Full Details

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#3]
As a **Site User**, I can **click on a Product on the list view** so that I can **view the full version of the Product's details, and view ratings and comments left by users**

**Acceptance Criteria**
- on clicking a Product the user is brought to the Full Product details view
- the Product information is clearly displayed
- the user can view ratings and comments left by users

**Task**
- [x] Link Product on list to full Product view
- [x] Make full Product's details easy to read and responsive
- [x] Show ratings and comments left by users on page
