### ISSUE TITLE
Sort Products

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#5]
As a **Shopper** I can **sort all Products** so that I can **I can find the products by type quickly**

**Acceptance Criteria**
- Within the browse products page a sort products drop-down menu is available to the user
- When the user clicks the drop-down arrow a list of pre-defined sort options appears
- When the user selects a sort option the page displays the products in that order

**Tasks**
- [ ]  Create sort selector on products page and add sort parameters to select box options
- [ ]   Add GET request to the all_products view to sort products
 - [ ]  Write javascript to update product list when sort select box is changed
