### ISSUE TITLE
New User Registration

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#8]
As a **Site User** I can **register and account** so that I can **have an account with my details saved**

**Acceptance Criteria**
- A signup button should be visible in the user drop down menu in the main navigation bar
- When the button is clicked the user is taken to the sign up page
- When the user fills in their details and clicks submit, they will receive an email verification link
- When they have confirmed, a new account will be created
- The user will receive a success message that a new account is created

**Tasks**
- [x]  Install allauth and add to installed apps
 - [x]  Add allauth urls
 - [x]  Add email verification requirement
 - [x]  Set up Gmail to send emails and add details to settings.py
 - [x]  Add signup link to navigation bar
 - [x]  Customise allauth signup form HTML templates
 - [x]  Create message to notify user of successful signup
