### ISSUE TITLE
User log in and log out

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/pureglow#9]
As a **Site User** I can **log in and log out of my account** so that I can **keep my account secure**

**Acceptance Criteria**
- Sign in button is visible on the navigation bar
- When I click the button I should be taken to the log in page
- When the user fills in their user name and password, and clicks submit they are logged in
- They then see a logged in success message
- If incorrect details are entered, they will see an error message
- The user can click a log out button and will be asked to confirm they wish to log out
- On confirmation, they will received a success message so they know they have successfully logged out

**Tasks**
- [x]  Install allauth and add to installed apps
 - [x] Add allauth urls
 - [x] Add log in and log out links to navigation bar
 - [x] Customise allauth login, logout HTML templates
 - [x] Create success messages for successful login/logout
